# Generated by Django 5.2.7 on 2025-10-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.CharField(choices=[('CENA', 'Cena'), ('COMIDA', 'Comida')], default='COMIDA', max_length=20)),
                ('pone_mesa', models.BooleanField(default=True)),
                ('quita_mesa', models.BooleanField(default=True)),
                ('mete_lava', models.BooleanField(default=False)),
                ('saca_lava', models.BooleanField(default=False)),
                ('num_fregados', models.IntegerField(default=0)),
            ],
        ),
    ]
