# Generated by Django 5.2.7 on 2025-10-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='era_mi_turno',
            field=models.BooleanField(default=True),
        ),
    ]
